apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/sh", "-c", "apt update && apt install -y openssh-server && service ssh start && sleep infinity"]
